### ISSUE TITLE
After job settings doesn't save

### ISSUE THREAD

**Issue by tonidas** [captmorgan/strawboss#1]
On the latest Jenkins, when you create a new strawboss job, the after job settings doesn't get persisted. It look like it's getting saved, but when you open the job config again, the settings disappear

**Comment by sco11morgan** [comment]
I've updated the plugin to fix this issue.  Please try version 1.3

The new code repo is at:
https://github.com/jenkinsci/strawboss-plugin

**Comment by sco11morgan** [comment]
Note there seems to be a problem sending email using the built in Jenkins mailer.  I was able to send email using the Email Extension Plugin.
